--liquibase formatted sql

--changeset alonzo:10_clinicas_fields
ALTER TABLE clinicas
ADD COLUMN nombre VARCHAR(200) NOT NULL,
ADD COLUMN tipo VARCHAR(50) NOT NULL,
ADD COLUMN ruc VARCHAR(11) NOT NULL,
ADD COLUMN diresa VARCHAR(100),
ADD COLUMN departamento VARCHAR(50) NOT NULL,
ADD COLUMN provincia VARCHAR(50) NOT NULL,
ADD COLUMN distrito VARCHAR(50) NOT NULL,
ADD COLUMN latitud DECIMAL(10,7),
ADD COLUMN longitud DECIMAL(10,7),
ADD COLUMN plan_saas VARCHAR(50) NOT NULL,
ADD COLUMN estado_suscripcion VARCHAR(50) NOT NULL,
ADD COLUMN max_pacientes INTEGER NOT NULL,
ADD COLUMN max_medicos INTEGER NOT NULL,
ADD CONSTRAINT uq_clinicas_ruc UNIQUE (ruc);

--rollback ALTER TABLE clinicas DROP CONSTRAINT IF EXISTS uq_clinicas_ruc;
--rollback ALTER TABLE clinicas DROP COLUMN IF EXISTS nombre, DROP COLUMN IF EXISTS tipo, DROP COLUMN IF EXISTS ruc, DROP COLUMN IF EXISTS diresa, DROP COLUMN IF EXISTS departamento, DROP COLUMN IF EXISTS provincia, DROP COLUMN IF EXISTS distrito, DROP COLUMN IF EXISTS latitud, DROP COLUMN IF EXISTS longitud, DROP COLUMN IF EXISTS plan_saas, DROP COLUMN IF EXISTS estado_suscripcion, DROP COLUMN IF EXISTS max_pacientes, DROP COLUMN IF EXISTS max_medicos;
